### ISSUE TITLE
C++ microbenchmarks are failing to post to Conbench after server update

### ISSUE THREAD

**Issue by austin3dickey** [voltrondata-labs/arrow-benchmarks-ci#163]
[Sample build logs.](https://buildkite.com/apache-arrow/arrow-bci-benchmark-on-ursa-thinkcentre-m75q/builds/3752#018a9cb8-be58-4a08-bed3-b55a8fc5686a)

```
230916-03:10:40.466 INFO: Benchmark run completed
230916-03:10:40.466 INFO: Transforming results for conbench
230916-03:10:40.492 WARNING: command `['sysctl', '-n', 'machdep.cpu.brand_string']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/machdep/cpu/brand_string: No such file or directory
230916-03:10:40.496 WARNING: command `['sysctl', '-n', 'hw.physicalcpu']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/physicalcpu: No such file or directory
230916-03:10:40.501 WARNING: command `['sysctl', '-n', 'hw.logicalcpu']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/logicalcpu: No such file or directory
230916-03:10:40.505 WARNING: command `['sysctl', '-n', 'hw.cpufrequency_max']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/cpufrequency_max: No such file or directory
230916-03:10:40.510 WARNING: command `['sysctl', '-n', 'hw.l1dcachesize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/l1dcachesize: No such file or directory
230916-03:10:40.514 WARNING: command `['sysctl', '-n', 'hw.l1icachesize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/l1icachesize: No such file or directory
230916-03:10:40.519 WARNING: command `['sysctl', '-n', 'hw.l2cachesize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/l2cachesize: No such file or directory
230916-03:10:40.524 WARNING: command `['sysctl', '-n', 'hw.l3cachesize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/l3cachesize: No such file or directory
230916-03:10:40.528 WARNING: command `['sysctl', '-n', 'hw.memsize']` returned with code 255, stderr prefix:
 sysctl: cannot stat /proc/sys/hw/memsize: No such file or directory
230916-03:10:40.561 WARNING: ignoring environment variable BENCHMARKABLE_PR_NUMBER with whitespace value: `''`
Traceback (most recent call last):
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/bin/conbench", line 8, in <module>
    sys.exit(conbench())
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/conbenchlegacy/cli.py", line 149, in _benchmark
    for result, output in benchmark().run(**kwargs):
  File "/var/lib/buildkite-agent/builds/ursa-thinkcentre-m75q-1/apache-arrow/arrow-bci-benchmark-on-ursa-thinkcentre-m75q/benchmarks/benchmarks/cpp_micro_benchmarks.py", line 125, in run
    self.adapter.run(command_params)
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/_adapter.py", line 100, in run
    self.results = self.transform_results()
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/_adapter.py", line 111, in transform_results
    results = self._transform_results()
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/archery.py", line 34, in _transform_results
    parsed_results += self._parse_suite(
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/archery.py", line 50, in _parse_suite
    result_parsed = self._parse_benchmark(
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/adapters/gbench.py", line 239, in _parse_benchmark
    res = BenchmarkResult(
  File "<string>", line 17, in __init__
  File "/var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/python3.8/site-packages/benchadapt/result.py", line 176, in _github_property
    raise ValueError(f"missing `repository` key in `github` property: {value}")
ValueError: missing `repository` key in `github` property: {}
```

**Comment by austin3dickey** [comment]
Caused by conbench/conbench#1484.
