### ISSUE TITLE
Arrow BCI Benchmark on ursa-i9-9960x > R TPCH benchmarks fail with Segmentation fault

### ISSUE THREAD

**Issue by ElenaHenderson** [voltrondata-labs/arrow-benchmarks-ci#63]
From buildkite logs:
```
INFO:root:Started executing -> conbench tpch --iterations=3 --all=true --drop-caches=true --run-id=$RUN_ID --run-name="$RUN_NAME"

/bin/bash: /var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/libtinfo.so.6: no version information available (required by /bin/bash)

INFO:root:/bin/bash: /var/lib/buildkite-agent/miniconda3/envs/arrow-commit/lib/libtinfo.so.6: no version information available (required by /bin/bash)

ERROR: {"timestamp": "2022-03-26T19:39:29.296245+00:00", "tags": {"cpu_count": null, "engine": "arrow", "memory_map": false, "query_id": "TPCH-01", "scale_factor": 10, "format": "parquet", "language": "R", "name": "tpch"}, "info": {"arrow_version": "8.0.0-SNAPSHOT", "arrow_compiler_id": "GNU", "arrow_compiler_version": "9.4.0", "benchmark_language_version": "R version 4.1.2 (2021-11-01)", "arrow_version_r": "7.0.0.9000"}, "context": {"arrow_compiler_flags": "-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /var/lib/buildkite-agent/miniconda3/envs/arrow-commit/include -fdiagnostics-color=always -O3 -DNDEBUG", "benchmark_language": "R"}, "error": "Segmentation fault (core dumped)", "command": "library(arrowbench); run_one(tpc_h, cpu_count=NULL, format='parquet', scale_factor=10, engine='arrow', memory_map=FALSE, query_id=1)"}

Traceback (most recent call last):

  File "/var/lib/buildkite-agent/builds/ursa-i9-9960x-1/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/benchmarks/benchmarks/_benchmark.py", line 224, in _get_benchmark_result

    result_path = self._get_results_path()

  File "/var/lib/buildkite-agent/builds/ursa-i9-9960x-1/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/benchmarks/benchmarks/_benchmark.py", line 232, in _get_results_path

    for file in os.listdir(f"results/{self.r_name}"):

FileNotFoundError: [Errno 2] No such file or directory: 'results/tpc_h'



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "/var/lib/buildkite-agent/builds/ursa-i9-9960x-1/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/benchmarks/benchmarks/_benchmark.py", line 201, in r_benchmark

    result, output = self._get_benchmark_result(command)

  File "/var/lib/buildkite-agent/builds/ursa-i9-9960x-1/apache-arrow/arrow-bci-benchmark-on-ursa-i9-9960x/benchmarks/benchmarks/_benchmark.py", line 228, in _get_benchmark_result

    raise Exception(error)

Exception: Segmentation fault (core dumped)
```

**Comment by austin3dickey** [comment]
Have not seen this in quite some time.
