### ISSUE TITLE
Arrow BCI Benchmark on voltron-pavilion > R TPCH-21 with SF = 10 benchmark gets killed because it tries to use more RAM than machine has

### ISSUE THREAD

**Issue by ElenaHenderson** [voltrondata-labs/arrow-benchmarks-ci#64]
From Buildkite logs:
```
ERROR: {"timestamp": "2022-03-28T23:49:47.635204+00:00", "tags": {"cpu_count": null, "engine": "arrow", "memory_map": false, "query_id": "TPCH-21", "scale_factor": 10, "format": "native", "language": "R", "name": "tpch"}, "info": {"arrow_version": "8.0.0-SNAPSHOT", "arrow_compiler_id": "GNU", "arrow_compiler_version": "10.3.0", "benchmark_language_version": "R version 4.1.3 (2022-03-10)", "arrow_version_r": "7.0.0.9000"}, "context": {"arrow_compiler_flags": "-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /var/lib/buildkite-agent/miniconda3/envs/arrow-commit/include -fdiagnostics-color=always -O3 -DNDEBUG", "benchmark_language": "R"}, "error": "Killed", "command": "library(arrowbench); run_one(tpc_h, cpu_count=NULL, format='native', scale_factor=10, engine='arrow', memory_map=FALSE, query_id=21)"}
--
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/voltron-pavilion-1/apache-arrow/arrow-bci-benchmark-on-voltron-pavilion/benchmarks/benchmarks/_benchmark.py", line 224, in _get_benchmark_result
  | result_path = self._get_results_path()
  | File "/var/lib/buildkite-agent/builds/voltron-pavilion-1/apache-arrow/arrow-bci-benchmark-on-voltron-pavilion/benchmarks/benchmarks/_benchmark.py", line 232, in _get_results_path
  | for file in os.listdir(f"results/{self.r_name}"):
  | FileNotFoundError: [Errno 2] No such file or directory: 'results/tpc_h'
  |  
  | During handling of the above exception, another exception occurred:
  |  
  | Traceback (most recent call last):
  | File "/var/lib/buildkite-agent/builds/voltron-pavilion-1/apache-arrow/arrow-bci-benchmark-on-voltron-pavilion/benchmarks/benchmarks/_benchmark.py", line 201, in r_benchmark
  | result, output = self._get_benchmark_result(command)
  | File "/var/lib/buildkite-agent/builds/voltron-pavilion-1/apache-arrow/arrow-bci-benchmark-on-voltron-pavilion/benchmarks/benchmarks/_benchmark.py", line 228, in _get_benchmark_result
  | raise Exception(error)
  | Exception: Killed
```

**Comment by austin3dickey** [comment]
I consider this "done" - no more benchmark failures due to this issue.
